loopback_users.guest = true
management.tcp.ip = 0.0.0.0
prometheus.tcp.ip = 0.0.0.0
prometheus.tcp.port = 15692
heartbeat = 30
channel_max = 512
consumer_timeout = 900000
vm_memory_high_watermark.relative = 0.60
disk_free_limit.absolute = 1GB
log.console.level = info
